# Generated by Django 4.2.1 on 2023-05-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_client_sampletype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="sampletype",
            field=models.CharField(
                choices=[("ش", "شامل"), ("ب", "بول"), ("ر", "روث")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="useradmin",
            name="gender",
            field=models.CharField(choices=[("ذ", "ذكر"), ("ث", "انثي")], max_length=1),
        ),
    ]
