# Generated by Django 4.2.1 on 2023-05-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_dynamicform_dynamicfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicfield",
            name="fieldvalue",
            field=models.FloatField(null=True),
        ),
    ]
