# Generated by Django 4.2.1 on 2023-06-05 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0005_alter_dynamicfield_fieldvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodChemistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("TotalProtien", models.FloatField()),
                ("Urea", models.FloatField()),
                ("Gluco", models.FloatField()),
                ("Calcium", models.FloatField()),
                ("Ck", models.FloatField()),
                ("LDH", models.FloatField()),
                ("AST_GOT", models.FloatField()),
                ("ALT_GPT", models.FloatField()),
                ("Albumin", models.FloatField()),
                ("Phosphorous", models.FloatField()),
                ("Creatinine", models.FloatField()),
                ("IRON", models.FloatField()),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodParasaite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "THELERIA",
                    models.CharField(
                        choices=[("P", "Positive"), ("N", "Negative")], max_length=1
                    ),
                ),
                (
                    "BABESIA",
                    models.CharField(
                        choices=[("P", "Positive"), ("N", "Negative")], max_length=1
                    ),
                ),
                (
                    "ANAPLASMA",
                    models.CharField(
                        choices=[("P", "Positive"), ("N", "Negative")], max_length=1
                    ),
                ),
                (
                    "TRYPANOSOMA",
                    models.CharField(
                        choices=[("P", "Positive"), ("N", "Negative")], max_length=1
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Haematology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("WBC", models.FloatField()),
                ("LYMPH", models.FloatField()),
                ("MONO", models.FloatField()),
                ("EOSIN", models.FloatField()),
                ("NEUT", models.FloatField()),
                ("RBC", models.FloatField()),
                ("HGB", models.FloatField()),
                ("HCT", models.FloatField()),
                ("MCV", models.FloatField()),
                ("MCH", models.FloatField()),
                ("MCHC", models.FloatField()),
                ("PLT", models.FloatField()),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intestinalparasites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "COCCIDIA",
                    models.CharField(
                        choices=[("F", "Found"), ("N", "Not Found")], max_length=1
                    ),
                ),
                (
                    "NEMATODE",
                    models.CharField(
                        choices=[("F", "Found"), ("N", "Not Found")], max_length=1
                    ),
                ),
                (
                    "CESTODE",
                    models.CharField(
                        choices=[("F", "Found"), ("N", "Not Found")], max_length=1
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.client",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="DynamicField",),
        migrations.DeleteModel(name="DynamicForm",),
    ]
