# Generated by Django 4.2.1 on 2023-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_analysisprices_alter_client_sampletype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useradmin",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="useradmin",
            name="username",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
